### ISSUE TITLE
No option for partial credit is also available.

### ISSUE THREAD

**Issue by hugomarins** [lovac42/MentalPause#2]
I installed the add-on today, and unlike the picture and info of the documentation, there is no option for using partial credits, only one option to fully disable Delay Bonus.

![image](https://user-images.githubusercontent.com/54500828/69011033-cffb4b00-0944-11ea-9613-f4327f0c32a8.png)

**Comment by lovac42** [comment]
Image for demo only, You click on it twice. One for box, twice for checkmark.
