### ISSUE TITLE
link to the manual section needs updating

### ISSUE THREAD

**Issue by guillempalau** [lovac42/MentalPause#3]
Anki manual has moved and the current link you have on [this shared add-on description](https://ankiweb.net/shared/info/1707633456) should be updated from
[https://apps.ankiweb.net/docs/manual.html#i-haven%E2%80%99t-studied-for-a-while,-and-now-the-next-due-times-are-too-big](https://apps.ankiweb.net/docs/manual.html#i-haven%E2%80%99t-studied-for-a-while,-and-now-the-next-due-times-are-too-big)  to
[https://docs.ankiweb.net/#/faqs?id=i-havent-studied-for-a-while-and-now-the-next-due-times-are-too-big](https://docs.ankiweb.net/#/faqs?id=i-havent-studied-for-a-while-and-now-the-next-due-times-are-too-big)

Cheers!

**Comment by lovac42** [comment]
thanks!
